version: '3'

services:
  
  api-server:
    build: ./
    entrypoint: [ "npm", "run", "dev" ]
    env_file: ./config/config.env
    ports:
      - '3000:3000'
    networks:
      - mysail-life-app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=mysail-life
    ports:
      - '27017:27017'
    networks:
      - mysail-life-app
    volumes:
      - mongo-data:/data/db

networks:
  mysail-life-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
