version: "3"

services:

  nodejs:
    image: gcr.io/mysail-life/app
    container_name: nodejs
    restart: unless-stopped
    entrypoint: [ "npm", "start" ]
    environment:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      MONGO_URI:

  gateway:
    image: gcr.io/mysail-life/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      URL: mysail.life
      VALIDATION: http
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - swag-data:/config

volumes:
  swag-data:
    driver: local
